use crate::{Description, Location, ResultExt, Stack, Top};

/// A trait representing the basic expectations for [doomstack](crate) errors.
///
/// Errors must describe themselves via [`Doom::tag`] (which should identify the error
/// type with a short, one-word, statically-defined tag, usually the type or variant of
/// the error) and [`Doom::description`] (which should provide a one-sentence description
/// of the error, and can be either statically or dynamically defined, see [`Description`]).
///
/// Optionally, a [doomstack](crate) error can override [`Doom::keep_original`] to indicate
/// whether or not the original error should be kept (in a [`Box<dyn Any>`], see
/// [`crate`]-level documentation) when the error is archived in an [`Entry`] (a default
/// implementation of [`Doom::keep_original`] is provided, which always returns `false`).
///
/// # Derivable
///
/// [`Doom`] can be derived for both structs and enums.
///
/// #### The `description` attribute
///
/// To derive [`Doom`], all you need to do is provide a `#[doom(description(...))]`
/// attribute for every group of fields in your type. This means: one description
/// per struct; one description per enum variant.
///
/// ```
/// # use doomstack::Doom;
/// #
/// #[derive(Doom)]
/// #[doom(description("Hose malfunctioned (pressure was {pressure}, {holes} holes formed)"))]
/// struct HoseError {
///     pressure: f32,
///     holes: u32,
/// }
///
/// #[derive(Doom)]
/// enum IrrigationError {
///     #[doom(description("Faucet broken"))]
///     FaucetBroken,
///     #[doom(description("Forgot to water for {days} days"))]
///     ForgotToWater { days: u32 },
/// }
/// ```
///
/// The `#[doom(description(...))]` attribute works very much like the [`format!`]
/// macro: one format string literal, optionally followed by arguments to format. If you
/// want to format the fields of your struct or variant, keep the following in mind:
///
///  - The `self` keyword is always at your disposal, capturing an immutable reference
///    to your type (struct or enum).
///  - If you are describing a group of named fields, every field is available to you
///    by its name, captured as an immutable reference.
///  - If you are describing a group of unnamed fields, every field is available to
///    you by its index, prefixed by an underscore (i.e., `_0`, `_1` and so on),
///    captured as an immutable reference.
///
/// This means that all of the following are allowed:
/// ```
/// # use doomstack::Doom;
/// #
/// #[derive(Doom)]
/// #[doom(description("Error code: {}, severity: {}, message: {_1}", self.0, self.severity()))]
/// struct TupleLikeError(u32, String);
///
/// impl TupleLikeError {
///     fn severity(&self) -> u32 {
///         // ...
///         # unimplemented!()
///     }
/// }
///
/// #[derive(Doom)]
/// enum EnumError {
///     #[doom(description("Error code: {code}, message: {message}"))]
///     NamedFields {
///         code: u32,
///         message: String
///     },
///     #[doom(description("Error code: {_0}, message: {_1}"))]
///     UnnamedFields(u32, String),
///     #[doom(description("Error code: {}", match self { EnumError::UnnecessarilyContrivedExample(code) => code, _ => unreachable!()}))]
///     UnnecessarilyContrivedExample(u32),
/// }
/// ```
///
/// #### The `wrap` attribute
///
/// Sometimes you will need to wrap some values (usually a non-[doomstack](crate) error,
/// possibly generated by some dependency that does not use [doomstack](crate)) inside
/// one of your errors. That is exactly what the `#[doom(wrap(...))]` attribute is for!
///
/// ##### Example
///
/// Let's start with a simple example:
/// ```
/// use doomstack::prelude::*;
///
/// #[derive(Doom)]
/// enum AgeError {
///     #[doom(description("Failed to read age: {source}"))]
///     #[doom(wrap(read_failed))]
///     ReadFailed {
///         source: std::io::Error,
///     },
///     #[doom(description("User is underage"))]
///     UnderageUser,
/// }
///
/// fn check_age<R>(mut handle: R) -> Result<(), Top<AgeError>>
///     where R: std::io::Read
/// {
///     # let mut buffer = [0u8; 4];
///     #
///     // ...
///     handle.read(&mut buffer).wrap(AgeError::read_failed)?;
///     // ...
///     #
///     # let age: u32 = unimplemented!();
///     
///     if age < 18 {
///         return AgeError::UnderageUser.fail();
///     }
///     
///     Ok(())
/// }
/// ```
/// In this example, we want to load a user's `age` from an `handle` (which implements
/// [`std::io::Read`]), then make sure that `age >= 18` (the user shouldn't be a minor).
/// As we discussed in the [`crate`]-level documentation, we scaffold an `AgeError` enum
/// with two variants:
///
///  - `AgeError::ReadFailed` indicates we failed to read `age` from `handle` (the `source`
///    field captures whatever [`std::io::Error`] `handle` produced when it failed to [`read`]).
///  - `AgeError::UnderageUser`, meaning the user is a minor.
///
/// As expected, our `check_age` function returns a `Top<AgeError>`. No surprises as far as
/// `AgeError::UnderageUser` is concerned, either: if `age < 18`, we simply return
/// `AgeError::UnderageUser.fail()`. What about `AgeError::ReadFailed`, though? Because
/// `handle.read()` does not return a [`Top`], we cannot simply
/// ```ignore
/// handle.read().push(AgeError::ReadFailed)?;
/// ```
/// Rather, if `handle.read()` returns an `Err(source)`, we must wrap `source` in an
/// `AgeError::ReadFailed`, which in turn has to be converted into a [`Top`]. Lacking
/// any syntax sugar, that would look something like this:
/// ```
/// # use doomstack::prelude::*;
/// #
/// # #[derive(Doom)]
/// # enum AgeError {
/// #     #[doom(description("Failed to read age: {source}"))]
/// #     #[doom(wrap(read_failed))]
/// #     ReadFailed {
/// #         source: std::io::Error,
/// #     },
/// #     #[doom(description("User is underage"))]
/// #     UnderageUser,
/// # }
/// #
/// # fn check_age<R>(mut handle: R) -> Result<(), Top<AgeError>>
/// #     where R: std::io::Read
/// # {
/// #     let mut buffer = [0u8; 4];
/// handle
///     .read(&mut buffer)
///     .map_err(|source| AgeError::ReadFailed { source }.into_top())?;
/// # unimplemented!()
/// # }
/// ```
/// A whole lot of code for a task this common! Luckily, `#[doom(wrap(...))]`
/// is there to cut down the boilerplate. By flagging `AgeError::ReadError`
/// with `#[doom(wrap(read_failed))]`, we have [`Doom`] derive a _wrapping
/// constructor_ `AgeError::read_failed`, whose implementation is equivalent
/// to
/// ```
/// # use doomstack::Doom;
/// #
/// # #[derive(Doom)]
/// # enum AgeError {
/// #     #[doom(description("Failed to read age: {source}"))]
/// #     ReadFailed {
/// #         source: std::io::Error,
/// #     },
/// #     #[doom(description("User is underage"))]
/// #     UnderageUser,
/// # }
/// #
/// impl AgeError {
///     fn read_failed(source: std::io::Error) -> Self {
///         AgeError::ReadFailed { source }
///     }
/// }
/// ```
/// Note the similarity with the lambda in our example above! All
/// `AgeError::read_failed` does is wrap a `source` of type [`std::io::Error`]
/// inside an `AgeError::ReadFailed`.
///
/// Once our wrapping constructor is derived, the [`ResultExt`] trait can take
/// care of the rest. In the example above, all we need to do is invoke
/// [`wrap`] on the [`Result`] produced by [`std::io::Read::read`]:
/// ```
/// # use doomstack::prelude::*;
/// #
/// # #[derive(Doom)]
/// # enum AgeError {
/// #     #[doom(description("Failed to read age: {source}"))]
/// #     #[doom(wrap(read_failed))]
/// #     ReadFailed {
/// #         source: std::io::Error,
/// #     },
/// #     #[doom(description("User is underage"))]
/// #     UnderageUser,
/// # }
/// #
/// # fn check_age<R>(mut handle: R) -> Result<(), Top<AgeError>>
/// #     where R: std::io::Read
/// # {
/// #     let mut buffer = [0u8; 4];
/// handle.read(&mut buffer).wrap(AgeError::read_failed)?;
/// # unimplemented!()
/// # }
/// ```
/// Provided with a wrapping constructor, [`wrap`] maps the [`Err`] variant of
/// a [`Result`] through the wrapping constructor first, then [`Doom::into_top`].
/// Note that this is exactly what we manually did in the boilerplate example
/// above. By the combined power of [`Doom`]'s `wrap` attribute and
/// [`ResultExt`]'s [`wrap`] method, foreign errors are as concise to propagate
/// as [`Top`]s!
///
/// ##### Deriving a wrapping constructor
///
/// Like `#[doom(description(...))]`, the `#[doom(wrap(...))]` attribute applies
/// to a group of fields, i.e., a struct or an enum variant. To cover both
/// cases, we will see what happens when we use `#[doom(wrap(constructor))]`
/// as an attribute for a struct `StructError` and a variant `EnumError::Variant`:
/// ```
/// # use doomstack::Doom;
/// #
/// #[derive(Doom)]
/// # #[doom(description("..."))]
/// // #[doom(description(...))]
/// #[doom(wrap(constructor))]
/// struct StructError // (Can be unit, named or tuple-like)
/// # ;
///
/// #[derive(Doom)]
/// enum EnumError {
///     # #[doom(description("..."))]
///     // #[doom(description(...))]
///     #[doom(wrap(constructor))]
///     Variant // (Can be unit, named or tuple-like)
/// }
/// ```
///
/// In both cases, [`Doom`] derives a wrapping constructor called
/// `constructor`: `StructError::constructor`, returning a
/// `StructError`, and `EnumError::constructor`, returning an
/// `EnumError::Variant`. Regardless of whether `StructError` /
/// `EnumError::Variant` are unit, named or tuple-like, `constructor`
/// always takes exactly one argument (this is to ensure that wrapping
/// constructors are always compatible with [`ResultExt`]'s [`wrap`]
/// interface):
///
///  - If `StructError` / `EnumError::Variant` are units, `constructor`
///    accepts but ignores any argument, blindly returning `StructError` /
///    `EnumError::Variant`. Intuitively, [`wrap`]-ing any error in a
///    unit amounts to throwing away the error and returning the unit.
///
///  - If `StructError` / `EnumError::Variant` are named or tuple-like,
///    `constructor` takes a tuple containing all `StructError`'s /
///    `EnumError::Variant`'s fields, in the order in which they appear
///    in the definition. Note the two special cases! If `StructError` /
///    `EnumError::Variant` have zero fields (e.g., `struct StructError {}`,
///    note the difference with `struct StructError;`, which is a unit)
///    then `constructor` takes the unit type (`()`). If `StructError` /
///    `EnumError::Variant` have exactly one field, then `constructor`
///    takes that field as only argument (indeed, Rust treats any
///    single-element tuple `(T)` as `T` itself).
///
///  This means that all of the following are allowed (to improve
///  readability, all `#[doom(description(...))]`s are omitted,
///  just remember they are not optional!):
/// ```
/// # use doomstack::Doom;
/// #
/// # #[derive(Debug, PartialEq)]
/// #[derive(Doom)]
/// # #[doom(description("..."))]
/// #[doom(wrap(constructor))]
/// struct Unit;
///
/// # #[derive(Debug, PartialEq)]
/// #[derive(Doom)]
/// # #[doom(description("..."))]
/// #[doom(wrap(constructor))]
/// struct EmptyTuple();
///
/// # #[derive(Debug, PartialEq)]
/// #[derive(Doom)]
/// # #[doom(description("..."))]
/// #[doom(wrap(constructor))]
/// struct SingleTuple(u32);
///
/// # #[derive(Debug, PartialEq)]
/// #[derive(Doom)]
/// # #[doom(description("..."))]
/// #[doom(wrap(constructor))]
/// struct MultiTuple(&'static str, &'static str);
///
/// # #[derive(Debug, PartialEq)]
/// #[derive(Doom)]
/// # #[doom(description("..."))]
/// #[doom(wrap(constructor))]
/// struct MultiNamed {
///     severity: u32,
///     description: &'static str,
/// };
///
/// # #[derive(Debug, PartialEq)]
/// #[derive(Doom)]
/// enum EnumError {
///     # #[doom(description("..."))]
///     #[doom(wrap(multi_named))]
///     MultiNamed {
///         severity: u32,
///         description: &'static str,
///     }
/// }
///
/// assert_eq!(Unit::constructor(()), Unit);
/// assert_eq!(Unit::constructor(42), Unit);
/// assert_eq!(Unit::constructor("Anything, really"), Unit);
///
/// assert_eq!(EmptyTuple::constructor(()), EmptyTuple());
/// assert_eq!(SingleTuple::constructor(42u32), SingleTuple(42));
///
/// assert_eq!(
///     MultiTuple::constructor(("multiple fields are packed", "in a tuple")),
///     MultiTuple("multiple fields are packed", "in a tuple")
/// );
///
/// assert_eq!(
///     MultiNamed::constructor((84u32, "order matters!")),
///     MultiNamed {
///         severity: 84,
///         description: "order matters!",
///     }
/// );
///
/// assert_eq!(
///     EnumError::multi_named((126u32, "variants work just like structs!")),
///     EnumError::MultiNamed {
///         severity: 126,
///         description: "variants work just like structs!",
///     }
/// );
///
/// ```
///
/// #### The `keep_original` attribute
///
/// When a [`Doom`] error is archived in an [`Entry`], by default the [`Entry`] captures
/// only the error's [`Doom::tag`] and [`Doom::description`]. If instructed to do
/// so by [`Doom::keep_original`], however, the [`Entry`] stores the original error
/// itself (in a [`Box<dyn Any>`], see [`Entry`] for additional information). The default
/// implementation of [`Doom::keep_original`] always returns `false`. The
/// `#[doom(keep_original)]` attribute is designed to quickly indicate which errors
/// should [`keep_original`].
///
/// If you want a struct error to always [`keep_original`], all you need to do is tag it
/// with `#[doom(keep_original)]`:
///
/// ```
/// # use doomstack::{Doom, Entry};
/// #
/// #[derive(Doom)]
/// # #[doom(description("..."))]
/// // #[doom(description(...))]
/// #[doom(keep_original)]
/// struct InfestationError {
///     parasites: u32,
/// }
///
/// let infestation_error = InfestationError { parasites: 1000 };
/// let infestation_entry = Entry::archive(infestation_error);
///
/// assert!(infestation_entry.original().is_some());
/// ```
///
/// For enums, it's more or less the same thing - just remember that `#[doom(keep_original)]`
/// applies to individual variants and not to the enum as a whole:
///
/// ```
/// # use doomstack::{Doom, Entry};
/// #
/// #[derive(Doom)]
/// enum WaterError {
///     # #[doom(description("..."))]
///     // #[doom(description(...))]
///     #[doom(keep_original)]
///     WaterTooHot { temperature: f32 },
///     # #[doom(description("..."))]
///     // #[doom(description(...))]
///     #[doom(keep_original)]
///     WaterTooHumid { humidity: f32 },
///     # #[doom(description("..."))]
///     // #[doom(description(...))]
///     WrongWaterColor,
/// }
///
/// let too_humid_error = WaterError::WaterTooHumid { humidity: 99.8 };
/// let too_humid_entry = Entry::archive(too_humid_error);
///
/// assert!(too_humid_entry.original().is_some());
///
/// let wrong_color_error = WaterError::WrongWaterColor;
/// let wrong_color_entry = Entry::archive(wrong_color_error);
///
/// assert!(wrong_color_entry.original().is_none());
/// ```
///
/// Note that, in the above example, `WaterError` doesn't [`keep_original`] if its
/// variant is `WrongWaterColor`!
///
/// If you need to specify more complex conditions for [`Doom::keep_original`] to
/// return `true`, simply add a boolean expression to your `#[doom(keep_original(...))]`
/// attribute:
///
/// ```
/// # use doomstack::{Doom, Entry};
/// #
/// #[derive(Doom)]
/// # #[doom(description("..."))]
/// // #[doom(description(...))]
/// #[doom(keep_original(*severity > 42))]
/// struct GroundError {
///     severity: u32
/// }
///
/// let insignificant_error = GroundError { severity: 42 };
/// let insignificant_entry = Entry::archive(insignificant_error);
///
/// assert!(insignificant_entry.original().is_none());
///
/// let serious_error = GroundError { severity: 43 };
/// let serious_entry = Entry::archive(serious_error);
///
/// assert!(serious_entry.original().is_some());
/// ````
///
/// As with `#[doom(description(...))]`, a `#[doom(keep_original(...))]` condition can
/// directly reference the fields of your struct or variant (we do exactly that in the
/// example above):
///
///  - The `self` keyword is always at your disposal, capturing an immutable reference
///    to your type (struct or enum).
///  - If you are expressing your condition on a group of named fields, every field is
///    available to you by its name, captured as an immutable reference.
///  - If you are expressing your condition on a group of unnamed fields, every field is
///    available to you by its index, prefixed by an underscore (i.e., `_0`, `_1` and so '
///    on), captured as an immutable reference.
///
/// # Manual implementation
///
/// An implementation of [`Doom`] must provide [`Doom::tag`] and [`Doom::description`].
/// Remember: [`Doom::tag`] should return a short, one-word, static identifier for
/// the error (you should probably just use the name of the relevant struct or enum
/// variant); [`Doom::tag`] should return a short, one-sentence description for the
/// error, and can be statically or dynamically defined (see [`Description`] for
/// additional information).
///
/// ```
/// use doomstack::{Description, Doom};
///
/// enum GardeningError {
///     TooMuchWater,
///     ForgotFertilizer,
///     DroppedFlowerpot { height: f64 },
/// }
///
/// impl Doom for GardeningError {
///     fn tag(&self) -> &'static str {
///         match self {
///             GardeningError::TooMuchWater => "GardeningError::TooMuchWater",
///             GardeningError::ForgotFertilizer => "GardeningError::ForgotFertilizer",
///             GardeningError::DroppedFlowerpot { .. } => "GardeningError::DroppedFlowerpot",
///         }
///     }
///
///     fn description(&self) -> Description {
///         match self {
///             GardeningError::TooMuchWater => {
///                 Description::Static("Added too much water, plants drowned")
///             }
///             GardeningError::ForgotFertilizer => {
///                 Description::Static("Forgot to add fertilizer, plants starved")
///             }
///             GardeningError::DroppedFlowerpot { height } => Description::Owned(format!(
///                 "Dropped flowerpot from {height} meters, plants crashed and many injured"
///             )),
///         }
///     }
/// }
/// ```
///
/// An additional method you might want to implement is [`Doom::keep_original`], which indicates
/// whether or not a copy of the original error should be kept (in a [`Box<dyn Any>`]) when the
/// error is archived in an [`Entry`]. A default implementation is provided, which always
/// returns `false`.
///
/// ```
/// use doomstack::{Description, Doom};
///
/// struct ToolError {
///     severity: u32,
///     tool: Tool,
/// }
///
/// enum Tool {
///     Rake,
///     Hose,
///     Spade,
/// }
///
/// impl Doom for ToolError {
///     fn tag(&self) -> &'static str {
///         "ToolError"
///     }
///
///     fn description(&self) -> Description {
///         Description::Static("Error involving a tool")
///     }
///
///     fn keep_original(&self) -> bool {
///         self.severity > 3
///     }
/// }
/// ```
///
/// [`doomstack`]: crate
/// [`Entry`]: crate::Entry
/// [`Box<dyn Any>`]: std::any::Any
/// [`keep_original`]: Doom::keep_original
/// [`read`]: std::io::Read::read
/// [`wrap`]: crate::ResultExt::wrap
pub trait Doom: 'static + Sized + Send + Sync {
    /// A short, one-word, statically defined tag, used to identify the error type.
    fn tag(&self) -> &'static str;

    /// A one-sentence description of the error. It can be either static or dynamic.
    fn description(&self) -> Description;

    /// Indicates whether or the original error should be kept (in a [`Box<dyn Any>`]) when
    /// the error is archived in an [`Entry`]. A default implementation of [`Doom::keep_original`]
    /// is provided, which always returns `false`.
    ///
    /// # Examples
    ///
    /// ```
    /// use doomstack::{Description, Doom, Entry};
    ///
    /// struct Oupsie(u64);
    ///
    /// impl Doom for Oupsie {
    ///     fn tag(&self) -> &'static str {
    ///         "Oupsie"
    ///     }
    ///
    ///     fn description(&self) -> Description {
    ///         Description::Static("Made a mess")
    ///     }
    ///
    ///     fn keep_original(&self) -> bool {
    ///         true
    ///     }
    /// }
    ///
    /// let oupsie = Oupsie(42);
    /// let entry = Entry::archive(oupsie);
    ///
    /// let value = entry
    ///     .original()
    ///     .unwrap()
    ///     .downcast_ref::<Oupsie>()
    ///     .unwrap();
    ///
    /// assert_eq!(value.0, 42);
    /// ```
    ///
    /// [`Entry`]: crate::Entry
    /// [`Box<dyn Any>`]: std::any::Any
    fn keep_original(&self) -> bool {
        false
    }

    /// Wraps `self` into a [`Top<Self>`] whose [`doom()`] is `self` and whose [`stack()`] has no entries.
    ///
    /// # Examples
    ///
    /// ```
    /// use doomstack::{Description, Doom};
    ///
    /// #[derive(Debug, Clone, PartialEq)]
    /// struct Oupsie(u64);
    ///
    /// impl Doom for Oupsie {
    ///     fn tag(&self) -> &'static str {
    ///         "Oupsie"
    ///     }
    ///
    ///     fn description(&self) -> Description {
    ///         Description::Static("Made a mess")
    ///     }
    /// }
    ///
    /// let oupsie = Oupsie(42);
    /// let top = oupsie.clone().into_top();
    ///
    /// assert_eq!(top.doom(), &oupsie);
    /// ```
    ///
    /// [`doom()`]: crate::Top::doom
    /// [`stack()`]: crate::Top::stack
    fn into_top(self) -> Top<Self> {
        Stack::new().push(self)
    }

    /// Wraps `self` into a [`Stack`] whose only [`Entry`] archives `self`.
    ///
    /// # Examples
    ///
    /// ```
    /// use doomstack::{Description, Doom};
    ///
    /// struct Oupsie;
    ///
    /// impl Doom for Oupsie {
    ///     fn tag(&self) -> &'static str {
    ///         "Oupsie"
    ///     }
    ///
    ///     fn description(&self) -> Description {
    ///         Description::Static("Made a mess")
    ///     }
    /// }
    ///
    /// let stack = Oupsie.into_stack();
    ///
    /// assert_eq!(stack.entries().next().unwrap().tag(), "Oupsie");
    /// ```
    ///
    /// [`Entry`]: crate::Entry
    fn into_stack(self) -> Stack {
        self.into_top().into()
    }

    /// Wraps `self` into a [`Top<Self>`] (as in [`Doom::into_top()`]), then into the `Err`
    /// variant of a [`Result`].
    ///
    /// # Examples
    ///
    /// ```
    /// use doomstack::{Description, Doom, Top};
    ///
    /// struct NotEven;
    ///
    /// impl Doom for NotEven {
    ///     fn tag(&self) -> &'static str {
    ///         "NotEven"
    ///     }
    ///
    ///     fn description(&self) -> Description {
    ///         Description::Static("The number provided is not even")
    ///     }
    /// }
    ///
    /// fn checked_half(n: u32) -> Result<u32, Top<NotEven>> {
    ///     if n % 2 == 0 {
    ///         Ok(n / 2)
    ///     } else {
    ///         NotEven.fail()
    ///     }
    /// }
    /// ```
    ///
    fn fail<O>(self) -> Result<O, Top<Self>> {
        Err(self.into_top())
    }

    /// Syntax sugar for [`Doom::fail`], then [`ResultExt::spot`].
    ///
    /// Calling `doom.fot(location)` is equivalent to calling `doom.fail().spot(location)`.
    fn fot<O>(self, location: Location) -> Result<O, Top<Self>> {
        self.fail().spot(location)
    }

    /// Wraps `self` into a `Stack` (as in [`Doom::into_stack()`]), then into the `Err`
    /// variant of a [`Result`].
    ///
    /// # Examples
    ///
    /// ```
    /// use doomstack::{Description, Doom, Stack};
    ///
    /// struct NotEven;
    ///
    /// impl Doom for NotEven {
    ///     fn tag(&self) -> &'static str {
    ///         "NotEven"
    ///     }
    ///
    ///     fn description(&self) -> Description {
    ///         Description::Static("The number provided is not even")
    ///     }
    /// }
    ///
    /// fn checked_half(n: u32) -> Result<u32, Stack> {
    ///     if n % 2 == 0 {
    ///         Ok(n / 2)
    ///     } else {
    ///         NotEven.fail_as_stack()
    ///     }
    /// }
    /// ```
    ///
    fn fail_as_stack<O>(self) -> Result<O, Stack> {
        Err(self.into_stack())
    }

    /// Syntax sugar for [`Doom::fail_as_stack`], then [`ResultExt::spot`].
    ///
    /// Calling `doom.fot_as_stack(location)` is equivalent to calling
    /// `doom.fail_as_stack().spot(location)` .
    fn fot_as_stack<O>(self, location: Location) -> Result<O, Stack> {
        self.fail_as_stack().spot(location)
    }
}
